---
apiVersion: v1
kind: Namespace
metadata:
  name: pacman
---
apiVersion: v1
kind: Secret
metadata:
  name: acm-app-secret
  namespace: pacman
data:
  accessToken: Z2hwX3FISnozZlQ3bGQ3dnhtQ0FmWjA2M0hGN0t5dU4xOTJvM0l2Rg==
  user: YXZhbGVyb3I=
type: Opaque
