---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: podinfo-app
  namespace: podinfo
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - podinfo-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
