---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
apiVersion: v1
kind: Secret
metadata:
  name: acm-app-secret
  namespace: podinfo
data:
  accessToken: YmM2M2JhNTFhOWI5MWY4N2ExMGY5ZmEzMGQ4Mzg1MzNmMzhkOGY5YQ==
  user: YXZhbGVyb3I=
type: Opaque
