apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: podinfo-app
  namespace: podinfo
  labels:
    app: podinfo-app
  annotations:
    apps.open-cluster-management.io/git-path: app-lifecycle/git/podinfo-app/podinfo
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: podinfo/podinfo-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: podinfo-pr
