---
- name: Test Slack Integration Module
  hosts: localhost
  vars:
    - slack_token: T01DXJFQCJJ/B01E19UC85T/v7d9Vb7ybV1lkZG97LsOomPC
    - app: Etherpad
  collections:
    - community.general
  tasks:
  - name: Send notification message via Slack
    #community.general.slack:
    slack:
      token: "{{slack_token}}"
      msg: 'The app "{{APPLICATION}}" is deployed in the cluster "{{CLUSTER}}"'
    delegate_to: localhost
